version: 2.1

jobs:
  build:
    working_directory: ~/circleci-project-setup
    docker:
      - image: python:3.8.10-alpine3.13
    steps:
      - checkout
      #- run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "requirements.txt"}}
      - run:
          name : install dependencies 
          command : |
            python3 -m pip install --upgrade pip
            apk --update --upgrade add gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev
            pip install -r requirements.txt
      - run:
          name : run application
          command : python billing_system.py
      - save_cache :
          key: cache-v1-{{ checksum "requirements.txt"}}
          paths:
            - "/usr/local/bin"

  test_billing_system_1:
    working_directory: ~/circleci-project-setup
    docker:
      - image: python:3.8.10-alpine3.13
    steps:
      - checkout
      #- run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "requirements.txt"}}
      - run:
          name : Running test case 1
          command : python test_billing_system_1.py
      - save_cache :
          key: cache-v1-{{ checksum "requirements.txt"}}
          paths:
            - "/usr/local/bin"

  test_billing_system_2:
    docker:
      - image: python:3.8.10-alpine3.13
    steps:
      - checkout
      #- run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "requirements.txt"}}
      - run:
          name : Running test case 2
          command : python test_billing_system_2.py
      - save_cache :
          key: cache-v1-{{ checksum "requirements.txt"}}
          paths:
            - "/usr/local/bin"

  docker_artifacts:
    working_directory: ~/circleci-project-setup
    docker:
      - image: python:3.8.10-alpine3.13
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "requirements.txt"}}
      - run:
          name : Install dependencies
          command : |
            apk --update --upgrade add docker docker-compose
      - run: docker build -t mahima_circleci -f Dockerfile.txt .
      - run: docker image ls
      - run:
          name: Save docker image 
          command: |
            mkdir -p /image_folder
            docker save -o /image_folder/mahima_circleci.tar mahima_circleci
      - store_artifacts:
          path: /image_folder
          destination: artifact-file
      # - save_cache:
      #     key: cache-v1-{{ checksum "requirements.txt"}}
      #     paths:
      #       - "/usr/local/bin"


workflows:
  circle-ci:
    # triggers:
    #   - schedule:
    #       cron: "0 17 * * *"
    #       filters:
    #        branches:
    #          only:
    #            - main
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - docker_artifacts:
          requires:
              - approval
      - test_billing_system_1:
          requires:
              - build
      - test_billing_system_2:
          requires:
              - build
      - approval:
          type: approval
          requires:
              - test_billing_system_1
              - test_billing_system_2